"""Add diary invites

Revision ID: 3632e1c5e000
Revises:
Create Date: 2017-09-25 21:14:24.743599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3632e1c5e000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diary_invites',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('guest_id', sa.Integer(), nullable=False),
                    sa.Column('guest_name', sa.String(length=128), nullable=False),
                    sa.Column('guest_relation', sa.Enum('Spouse', 'Child', 'Sibling', 'Parent', 'Other', name='guestrelation'),
                              nullable=False),
                    sa.Column('status', sa.Enum('Sent', 'Accepted', 'Declined', name='invitestatus'), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_diary_invites_guest_id'), 'diary_invites', ['guest_id'], unique=False)
    op.create_index(op.f('ix_diary_invites_user_id'), 'diary_invites', ['user_id'], unique=False)
    op.add_column('users', sa.Column('birth_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('death_year', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('life_story', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('life_title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'life_title')
    op.drop_column('users', 'life_story')
    op.drop_column('users', 'death_year')
    op.drop_column('users', 'birth_year')
    op.drop_index(op.f('ix_diary_invites_user_id'), table_name='diary_invites')
    op.drop_index(op.f('ix_diary_invites_guest_id'), table_name='diary_invites')
    op.drop_table('diary_invites')
    # ### end Alembic commands ###
